services:
  npm:
    build:
      context: .
      dockerfile: ./npm/Dockerfile
    container_name: marianmt-npm
    ports:
      - "3000:3000"
    volumes:
      - ./models:/models
      - ./voices:/voices
      - ./flags:/flags
    restart: unless-stopped
    environment:
      - PORT=3000

